@url = http://localhost:8080/api/reviews

### POST - Happy path 

POST {{url}}/review HTTP/1.1
Content-Type: application/json

{   
    "userId": 1,
    "gameId": 2,
    "text": "Testing text",
    "rating": 8
}

### GET - successful get all reviews - 200 
GET {{url}} HTTP/1.1